ML=read.csv("ML")
TS=read.csv("TS")
bio=read.csv("bio")
hist(bio$grade,col='grey',breaks=12,prob=TRUE)
lines(density(bio$grade),lwd=2)
dev.new()
hist(ML$grade,col='grey',breaks=12,prob=TRUE)
lines(density(ML$grade),lwd=2)
dev.new()
hist(TS$grade,col='grey',breaks=12,prob=TRUE)
lines(density(TS$grade),lwd=2)

